### ISSUE TITLE
using PHP 5.6.*

### ISSUE THREAD

**Issue by ghost** [lukevear/jwt-auth-guard#3]
I think it is save when using PHP 5.6. Please let me know why this package have to use PHP 7.0

**Comment by lukevear** [comment]
This package hasn't been tested on PHP 5.6.

If you are able to test with 5.6, please feel free to give it a run and send through a pull request with whatever changes are necessary.

**Comment by ghost** [comment]
how did you do the test for php 7.0? I don't see any test script in this repository

**Comment by lukevear** [comment]
This package was built on my dev machine with 7.0.

**Comment by ghost** [comment]
ok, I will say that I change php 7.0 to 5.6, and it work fine. And one more thing, lumen / laravel use php 5.6.4 for minimum requirement. It is not make any sense that your package doesn't support that.
